### ISSUE TITLE
Embedded app with events and news

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1479]
- [x] #1440 Improve data structure so we can handle periodic events better
    - [x] Change dates structure
    - ~[ ] Save 'event type' (cursus/creativiteit/gezondheid/voeding/...) or whatever it's called so we can filter on it. No event types for google calendar events~ later 
- [x] Make it possible to open embedded app from service menu item. Embedded app should receive some context (the menu item that was used to open it)
    - [x] Server + web UI
    - [x] Android
    - [x] iOS
- [x] Embedded app should be able to execute getNewsGroups and getNewsItems calls (bridge between javascript and ios/android rpc calls, use some generic handler that can be easily reused like the IntentResponseHandler on android)
   - [x] Android
   - [x] iOS
- [x] Method to open a specific news group from js (extend rogerthat.open)
- [x] #1479 Create embedded app to be used for various OCA stuff (starting with events). No actual functionality yet.
- [x] List of agenda events
- [x] List of news items
- [x] Filter agenda events page 
  - textfield
  - time: Vandaag, Morgen, dit weekend, Volgende 7 dagen, Volgende 14 dagen, Volgende 30 dagen, Kies een datum
- [x] Index events in search index (id, title, description, every timeframe)
- [x] Event detail page

![Screenshot 2019-10-01 at 14 16 30](https://user-images.githubusercontent.com/17762105/65961066-17da1780-e456-11e9-911f-5fa9bdd2c61f.png)

**Comment by lucasvanhalst** [comment]
Tasks:
- [ ] #1440 Improve data structure so we can handle periodic events better
    - Change dates structure
    - Save 'event type' (cursus/creativiteit/gezondheid/voeding/...) or whatever it's called so we can filter on it. No event types for google calendar events 
- [ ] Make it possible to open embedded app from service menu item. Embedded app should receive some context (the menu item that was used to open it)
    - [ ] Server + web UI
    - [ ] Android
    - [ ] iOS
- [ ] Embedded app should be able to execute getNewsGroups and getNewsItems calls (bridge between javascript and ios/android rpc calls, use some generic handler that can be easily reused like the IntentResponseHandler on android)
   - [ ] Android
   - [ ] iOS
- [ ] System.api call to fetch agenda filters (only `types` for now)
- [ ] System.api call to fetch agenda items with or without `types` filter
- [ ] #1479 Create embedded app to be used for various OCA stuff (starting with events). No actual functionality yet.
- [ ] Create generic 'loading/error' component to be used everywhere
- [ ] List of agenda events
- [ ] List of news items
- [ ] Filter agenda events page
- [ ] Event detail page
